### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by HungryCustomer** [oscarchilds/dock-menu#1]
```
Error: { Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
```

**Comment by oscarchilds** [comment]
Hey,

The API is currently down, I will look into this at the next possible opportunity!

**Comment by oscarchilds** [comment]
Api is up!
