### ISSUE TITLE
Error: Service Hangs, then return error

### ISSUE THREAD

**Issue by remmus** [oscarchilds/dock-menu#2]
```
Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.socketOnEnd (_http_client.js:440:23)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
```

Needed to get my snack on but the menu seems to be down.

Had to go in there and accosted by Riccardo, felt utterly ashamed to walk out empty handed as I didn't want any of his wares.

**Comment by oscarchilds** [comment]
Hey,

Sorry that our downtime caused you this inconvenience! Next time I suggest buying something you didn't plan on buying as to avoid the awkward "empty handed" shuffle away from the dock. This is the same issue we're seeing in #1 , so we should be up again soon!

**Comment by oscarchilds** [comment]
Api is back in action!
